services:
- type: worker
  name: qwenzy-bot
  env: node
  region: frankfurt
  buildCommand: npm install
  startCommand: npm start
  envVars:
  - key: NODE_VERSION
    value: 20
  - key: DISCORD_TOKEN
    sync: false
  - key: CLIENT_ID
    sync: false
  - key: GUILD_ID
    sync: false
  - key: GEMINI_API_KEY
    sync: false